version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py superuser_create && python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    command: sh -c "npm cache clean --force && npm install && npm start"


  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_user
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

